/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 867939db08d92a8275836c2f75cceeb8)
interface __BaseEnv_Env {
	DB: D1Database;
	BETTER_AUTH_URL: "https://api.file.thanejoss.com";
	APP_ORIGIN: "https://file.thanejoss.com";
	BETTER_AUTH_SECRET: string;
	TURN_KEY_ID: string;
	TURN_KEY_API_TOKEN: string;
	R2_ACCOUNT_ID: string;
	R2_BUCKET: string;
	R2_PARENT_API_TOKEN: string;
	R2_PARENT_ACCESS_KEY_ID: string;
	SFU_APP_ID: string;
	SFU_APP_TOKEN: string;
	PICKUP_SESSIONS: DurableObjectNamespace<import("./src/index").PickupSession>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./src/index");
		durableNamespaces: "PickupSession";
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "BETTER_AUTH_URL" | "APP_ORIGIN" | "BETTER_AUTH_SECRET" | "TURN_KEY_ID" | "TURN_KEY_API_TOKEN" | "R2_ACCOUNT_ID" | "R2_BUCKET" | "R2_PARENT_API_TOKEN" | "R2_PARENT_ACCESS_KEY_ID" | "SFU_APP_ID" | "SFU_APP_TOKEN">> {}
}
